station_names = {
    "MIT Pacific St at Purrington St",
    "Central Square at Mass Ave / Essex St",
    "Inman Square at Vellucci Plaza / Hampshire St",
    "Harvard Law School at Mass Ave / Jarvis St",
    "Charles Circle - Charles St at Cambridge St",
    "Wilson Square",
    "Packard's Corner - Commonwealth Ave at Brighton Ave",
    "Copley Square - Dartmouth St at Boylston St",
    "Watermark Seaport - Boston Wharf Rd at Seaport Blvd",
    "Cross St at Hanover St",
    "Boylston St at Washington St",
    "Third at Binney",
    "Rowes Wharf at Atlantic Ave",
    "Commonwealth Ave at Buick St",
    "Harvard University Radcliffe Quadrangle at Shepard St / Garden St",
    "MIT Vassar St",
    "Allston Green District - Griggs St at Commonwealth Ave",
    "Boylston St at Massachusetts Ave",
    "Harvard Square at Brattle St / Eliot St",
    "Kenmore Square",
    "University Park",
    "Harvard University River Houses at DeWolfe St / Cowperthwaite St",
    "Brigham Circle - Francis St at Huntington Ave",
    "Harvard Square at Mass Ave/ Dunster",
    "Beacon St at Massachusetts Ave",
    "Prudential Center - Belvedere St",
    "Beacon St at Arlington St",
    "Boylston St at Arlington St",
    "Jackson Square T Stop",
    "South Station - 700 Atlantic Ave",
    "Main St at Austin St",
    "Andrew T Stop - Dorchester Ave at Dexter St",
    "E Cottage St at Columbia Rd",
    "Union Square - Brighton Ave at Cambridge St",
    "Cambridge St at Joy St",
    "Powder House Circle - Nathan Tufts Park",
    "Washington St at Waltham St",
    "Ink Block - Harrison Ave at Herald St",
    "Wentworth Institute of Technology - Huntington Ave at Vancouver St",
    "Lesley University",
    "Verizon Innovation Hub 10 Ware Street",
    "Yawkey Way at Boylston St.",
    "W Broadway at Dorchester St",
    "Harvard University Housing - 115 Putnam Ave at Peabody Terrace",
    "Lewis Wharf at Atlantic Ave",
    "W Broadway at D St",
    "Porter Square Station",
    "Warren St at Chelsea St",
    "Columbus Ave at Massachusetts Ave",
    "Boston Medical Center - E Concord St at Harrison Ave",
    "Coolidge Corner - Beacon St @ Centre St",
    "Boylston St at Fairfield St",
    "Tremont St at E Berkeley St",
    "Green Street T Stop - Green St at Amory St",
    "Washington St at Rutland St",
    "Kendall T",
    "Boston City Hall - 28 State St",
    "Lower Cambridgeport at Magazine St/Riverside Rd",
    "Dorchester Ave at Gillette Park",
    "Washington St at Lenox St",
    "Newbury St at Hereford St",
    "Back Bay T Stop - Dartmouth St at Stuart St",
    "Silber Way",
    "Longwood Ave at Binney St",
    "Bowdoin St at Quincy St",
    "Linear Park - Mass. Ave. at Cameron Ave. ",
    "Charles st and Beacon St",
    "Soldiers Field Park - 111 Western Ave",
    "Ruggles T Stop - Columbus Ave at Melnea Cass Blvd",
    "175 N Harvard St",
    "South Boston Library - 646 E Broadway",
    "Northeastern University - North Parking Lot",
    "Somerville City Hall",
    "Egleston Square - Atherton St at Washington St",
    "359 Broadway - Broadway at Fayette Street",
    "Cambridge St - at Columbia St / Webster Ave",
    "Congress St at Northern Ave",
    "Nashua Street at Red Auerbach Way",
    "Cambridge Main Library at Broadway / Trowbridge St",
    "Curtis Hall - South St at Centre St",
    "Hyde Square - Barbara St at Centre St",
    "Kendall Street",
    "ID Building East",
    "Arch St at Franklin St",
    "Park Dr at Buswell St",
    "Glendon St at Condor St",
    "Danehy Park",
    "Surface Rd at India St",
    "Burlington Ave at Brookline Ave",
    "Edwards Playground - Main St at Eden St",
    "Ames St at Main St",
    "Boylston St at Berkeley St",
    "Aquarium T Stop - 200 Atlantic Ave",
    "Central Sq Post Office / Cambridge City Hall at Mass Ave / Pleasant St",
    "State Street at Channel Center",
    "Brookline Village - Station Street @ MBTA",
    "Washington Square at Washington St. / Beacon St.",
    "Airport T Stop - Bremen St at Brooks St",
    "MIT at Mass Ave / Amherst St",
    "Murphy Skating Rink - 1880 Day Blvd",
    "Spaulding Rehabilitation Hospital - Charlestown Navy Yard",
    "Clarendon Hill at Broadway",
    "Congress St at Sleeper St",
    "Seaport Square - Seaport Blvd at Northern Ave",
    "Dana Park",
    "Christian Science Plaza - Massachusetts Ave at Westland Ave",
    "Beacon St at Washington / Kirkland",
    "MIT Stata Center at Vassar St / Main St",
    "Brighton Center - Washington St at Cambridge St",
    "TD Garden - West End Park",
    "Hayes Square - Vine St at Moulton St",
    "Lafayette Square at Mass Ave / Main St / Columbia St",
    "Chinatown Gate Plaza",
    "Washington St at Melnea Cass Blvd",
    "Union Square - Somerville",
    "Roxbury Crossing T Stop - Columbus Ave at Tremont St",
    "Mt Auburn",
    "Ryan Playground - Dorchester Ave at Harbor View St",
    "Tremont St at West St",
    "Harvard Kennedy School at Bennett St / Eliot St",
    "South End Library - Tremont St at W Newton St",
    "One Kendall Square at Hampshire St / Portland St",
    "NCAAA - Walnut Ave at Crawford St",
    "JFK Crossing at Harvard St. / Thorndike St.",
    "Colleges of the Fenway - Fenway at Avenue Louis Pasteur",
    "CambridgeSide Galleria - CambridgeSide PL at Land Blvd",
    "Lechmere Station at Cambridge St / First St",
    "Commonwealth Ave At Babcock St",
    "Teele Square at 239 Holland St",
    "Rindge Avenue - O'Neill Library",
    "Magoun Square at Trum Field",
    "One Broadway / Kendall Sq at Main St / 3rd St",
    "Newmarket Square T Stop - Massachusetts Ave at Newmarket Square",
    "S Huntington Ave at Heath St",
    "Davis Square",
    "EF - North Point Park",
    "Boylston St at Dartmouth St",
    "Museum of Science",
    "Bunker Hill Community College",
    "Seaport Hotel - Congress St at Seaport Ln",
    "Purchase St at Pearl St",
    "Congress St at North St",
    "Alewife Station at Russell Field",
    "Brian P. Murphy Staircase at Child Street",
    "Stuart St at Charles St",
    "Conway Park - Somerville Avenue",
    "Harvard University Gund Hall at Quincy St / Kirkland S",
    "B.U. Central - 725 Comm. Ave.",
    "Landmark Center - Brookline Ave at Park Dr",
    "Brighton Mills - 370 Western Ave",
    "Washington St at Brock St",
    "JFK/UMass T Stop",
    "Packard Ave / Powderhouse Blvd",
    "Chelsea St at Saratoga St",
    "Fan Pier",
    "Savin Hill T Stop - S Sydney St at Bay St",
    "Binney St / Sixth St",
    "New Balance - 20 Guest St",
    "Post Office Square - Pearl St at Milk St",
    "Sidney Research Campus/ Erie Street at Waverly",
    "Oak Square - 615 Washington St",
    "Central Square - East Boston",
    "MLK Blvd at Washington St",
    "The Lawn on D",
    "Piers Park",
    "Upham's Corner",
    "Roxbury YMCA - Warren St at MLK Blvd",
    "Alewife MBTA at Steel Place",
    "Harvard University / SEAS Cruft-Pierce Halls at 29 Oxford St",
    "HMS/HSPH - Avenue Louis Pasteur at Longwood Ave",
    "Fresh Pond Reservation",
    "Boston Convention and Exhibition Center - Summer St at West Side Dr",
    "Franklin Park - Seaver St at Humbolt Ave",
    "Maverick Square - Lewis Mall",
    "Dudley Square - Dudley St at Warren St",
    "Upham's Corner T Stop - Magnolia St at Dudley St",
    "Innovation Lab - 125 Western Ave at Batten Way",
    "ID Building West",
    "Grove Hall Library - 41 Geneva Ave",
    "Orient Heights T Stop - Bennington St at Saratoga St",
    "East Boston Neighborhood Health Center - 20 Maverick Square",
    "Broadway St at Mt Pleasant St",
    "University of Massachusetts Boston - Integrated Sciences Complex",
    "The Eddy - New St at Sumner St",
    "Bennington St at Byron St",
    "18 Dorrance Warehouse",
    "Franklin Park Zoo - Franklin Park Rd at Blue Hill Ave",
    "Walnut Ave at Warren St",
    "Columbia Rd at Ceylon St",
    "Cambridge Dept. of Public Works -147 Hampshire St.",
    "Huntington Ave at Mass Art",
    "Kennedy-Longfellow School 158 Spring St",
    "Galileo Galilei Way at Main Street",
    "700 Commonwealth Ave.",
    "Stony Brook T Stop",
    "Dudley Square - Bolling Building",
    "Albany St at E. Brookline St",
    "Mass Ave at Albany St",
    "Park Plaza at Charles St S.",
    "Franklin Park - Seaver St at Humboldt Ave",
    "Coolidge Corner - Beacon St at Centre St",
    "Mugar Way at Beacon St",
    "Commonwealth Ave at Chiswick Rd",
    "Mass Ave T Station",
    "Coolidge Sq.",
    "Harvard St at Greene-Rose Heritage Park",
    "Government Center - Cambridge St at Court St",
    "Ring Rd",
    "Faneuil St at Arlington St",
    "Harrison Ave at Bennet St",
    "Boylston St at Jersey St",
    "30 Dane St",
    "Columbia Rd at Tierney Community Center",
    "Boston Public Market",
    "Harrison Ave at Mullins Way",
    "75 Binney St",
    "Prudential Center - 101 Huntington Ave",
    "Beacon St at Tappan St",
    "Berkshire Street at Cambridge Street",
    "Commonwealth Ave at Griggs St",
    "Thorndike Field at Minuteman Bikeway",
    "Stuart St at Berkeley St",
    "Edgerly Education Center",
    "Columbus Ave at W. Canton St",
    "Chinatown T Stop",
    "Harvard Ave at Brainerd Rd",
    "Inman Square at Springfield St.",
    "Community Path at Lowell St",
    "Dartmouth St at Newbury St",
    "Sullivan Square",
    "Tremont St at W. Dedham St",
    "Troy Boston",
    "Lansdowne T Stop",
    "The Overlook at St. Gabriel's",
    "Sennott Park Broadway at Norfolk Street",
    "Deerfield St at Commonwealth Ave",
    "Tremont St at Northampton St",
    "Seaport Blvd at Sleeper St",
    "Lower Cambridgeport at Magazine St / Riverside Rd",
    "St Mary's",
    "Child St at North St",
    "Huron Ave At Vassal Lane",
    "Broadway at Central St",
    "Williams St at Washington St",
    "Watertown Sq",
    "Brookline Village - Station Street at MBTA",
    "Foss Park",
    "Bartlett St at John Elliot Sq",
    "191 Beacon St",
    "Main St at Baldwin St",
    "Main St at Thompson Sq",
    "Sidney Research Campus/Erie Street at Waverly",
    "Cleveland Circle",
    "700 Huron Ave",
    "Commonwealth Ave at Kelton St",
    "Forest Hills",
    "Perry Park",
    "Tremont St at Hamilton Pl",
    "Surface Rd at Summer St",
    "Nonantum Library",
    "Charlestown Navy Yard",
    "Shawmut Ave at Oak St W",
    "One Memorial Drive",
    "Brookline Town Hall",
    "Vassal Lane at Tobin/VLUS",
    "Honan Library",
    "One Brigham Circle",
    "Elm St at White St",
    "Packard Ave at Powderhouse Blvd",
    "Graham and Parks School – Linnaean St at Walker St",
    "East Somerville Library (Broadway and Illinois)",
    "Somerville City Hall Annex",
    "Grove St at Community Path",
    "699 Mt Auburn St",
    "Rogers St & Land Blvd",
    "Craigie at Summer St",
    "Assembly Square T",
    "MIT Carleton St at Amherst St",
    "645 Summer St",
    "Boylston St at Charles St",
    "Roslindale Village - Washington St",
    "Ames St at Broadway",
    "Boylston St at Exeter St",
    "Medford St at Charlestown BCYF",
    "MIT Hayward St at Amherst St",
    "Geiger Gibson Community Health Center",
    "Commonwealth Ave at Agganis Way",
    "Tappan St at Brookline Hills MBTA",
    "West End Park",
    "Bennington St at Constitution Beach",
    "Harvard Stadium: N. Harvard St at Soldiers Field Rd",
    "Harrison Ave at E. Dedham St",
    "Washington St at Myrtle St",
    "Central Square East Boston",
    "Sydney St at Carson St",
    "Ball Sq",
    "Ashmont T Stop",
    "Congress St at Boston City Hall",
    "Chelsea St at Vine St",
    "Arsenal Yards",
    "Maverick St at Massport Path",
    "Fields Corner T Stop",
    "Harvard University Gund Hall at Quincy St / Kirkland St",
    "Hyde Park Ave at Walk Hill St",
    "Whittier St Health Center",
    "Somerville Hospital",
    "N. Beacon St at N. Beacon Ct",
    "7 Acre Park",
    "Farragut Rd at E. 6th St",
    "Martha Eliot Health Center",
    "Gallivan Blvd at Adams St",
    "Shawmut T Stop",
    "Teele Square",
    "Broadway at Lynde St",
    "Bacon St at Washington St",
    "Mass Ave at Hadley/Walden",
    "Boston Landing",
    "84 Cambridgepark Dr",
    "Discovery Park - 30 Acorn Park Drive",
    "Community Path at Cedar Street",
    "Wasgatt Playground",
    "Swan St. Park",
    "Centre St at W. Roxbury Post Office",
    "Centre St at Parkway YMCA",
    "Hale Park",
    "Encore",
    "Glendale Square (Ferry St at Broadway)",
    "Spring St at Powell St",
    "Everett Square (Broadway at Chelsea St)",
    "Smith Pl at Wilson Rd",
    "Boston East - 126 Border St",
    "Kearins Playground",
    "Mattapan Library",
    "Talbot Ave At Blue Hill Ave",
    "Broadway at Beacham St",
    "BCBS Quincy",
    "Langley Lot",
    "West Newton",
    "Washington St at Crafts St",
    "Blue Hill Ave at Havelock St",
    "Jamaica St at South St",
    "The Dimock Center",
    "Revere City Hall",
    "Roslindale Village - South St",
    "Belgrade Ave at Walworth St",
    "Codman Square Library",
    "Mattapan T Stop",
    "Day Sq",
    "Centre St at Washington St",
    "Porzio Park",
    "Blue Hill Ave at Almont St",
    "American Legion Hwy at Canterbury St",
    "Revere Public Library",
    "Union St at Herrick Rd – Newton Centre Green Line",
    "Gove St at Orleans St",
    "Four Corners - 157 Washington St",
    "Washington St at Talbot Ave",
    "University of Massachusetts Boston - Campus Center",
    "Beacon St at St. Paul St",
    "Watertown Town Hall",
    "Washington St @ New Washington St (Temp Winter Station)",
    "Trum Field @ Cedar St (Temp Winter Station)",
    "Union Square East (Temp Winter Station)",
    "Broadway Opposite Norwood Ave  (Temp Winter Station)",
    "Conway Park @ Bleachery Ct (Temp Winter Station)",
    "2 Hummingbird Lane at Olmsted Green",
    "West Newton Armory",
    "Everett Square (Broadway at Norwood St)",
    "Broadway at Maple St",
    "St. Alphonsus St at Tremont St",
    "Broad Canal Way at Third Street",
    "Hawthorne Boulevard",
    "Beacon St at Charles St",
    "Forsyth St at Huntington Ave",
    "606 American Legion Hwy at Canterbury St",
    "160 Arsenal St",
    "Danehy Park at New Street",
    "Child Street at Brian P. Murphy Staircase",
    "Uphams Corner T Stop - Magnolia St at Dudley St",
    "Chestnut St at Poplar St",
    "Hood Park",
    "Parker St at Huntington Ave",
    "Harvard St and Stedman St",
    "Vinnin Square",
    "Moore Youth Center",
    "Meaney Playground - Pleasant St at E Cottage St",
    "Beach St at Freeport St",
    "955 Mass Ave",
    "Union Square East",
    "Old Morse Park at Putnam Ave",
    "Lincoln St at Empire St",
    "Washington St at Egremont Rd",
    "Main St at Brooks Park",
    "Mayor Salvo Path at Mill St",
    "Centre St at Seaverns Ave",
    "California at Chapel",
    "Medford Sq - Riverside Ave at River St",
    "Union Square Station",
    "O'Brien Highway at First Street",
    "Northbourne Rd at Hyde Park Ave",
    "Morgan Ave at North First St",
    "Salem MBTA - Washington at Federal St",
    "Concord Ave at Spinelli Place",
    "Galileo Galilei Way at Fulkerson St/Binney St",
    "Talbot Ave T Station",
    "Salem Willows Park",
    "Washington St at Bowdoin St",
    "Foley St at Grand Union Blvd",
    "Pier 4 Blvd at Autumn Ln",
    "High St at Cypress St",
    "Knoll St at Centre St",
    "Washington St at Denton Terr",
    "Gore Street at Lambert Street",
    "Marion St at Harvard St",
    "Washington St at Fuller St",
    "Ross Playground",
    "Bridge Street Neck",
    "Salem State University - Bike Path at Loring Ave",
    "Cleary Sq",
    "Essex St at Dalton Parkway",
    "Central Ave at River St",
    "Washington St at Walnut St",
    "West Medford Square (Bower St at Harvard Ave)",
    "Somerville High School & Central Library",
    "Hormel Stadium",
    "1200 Beacon St",
    "Commonwealth Ave at Naples Rd",
    "Church St",
    "Valenti Way at Haverhill St",
    "Washington St at Walsh Playground",
    "Hyde Park Library",
    "Butler T Stop",
    "555 Metropolitan Ave",
    "Orr Sq (Shirley Ave)",
    "Watertown St at Albemarle Rd",
    "Shawmut Ave at Lenox St",
    "Adams St at Lonsdale St",
    "Gramsdorf Playground",
    "Hancock St at Pleasant St",
    "Railroad Lot and Minuteman Bikeway",
    "325 Binney St.",
    "on",
    "John Ahern Field at Kennedy-Longfellow School",
    "Mass Ave/Lafayette Square",
    "Clarendon St at Newbury St",
    "Shetland Park - Congress at Peabody St",
    "Broadway T Stop",
    "Cedar Grove T Stop",
    "Auburn St. at Mystic River",
    "Broad St at Central St",
    "Cambridge Crossing at North First Street",
    "Four Corners/Geneva T Stop",
    "Circuit Drive at American Legion Hwy",
    "Haines Square",
    "Bremen St at Marion St",
    "Walnut Ave at School St",
    "Harris Park",
    "Massachusetts Ave at Columbus Ave",
    "Lafayette at Leach St",
    "Newton Library",
    "87-101 Cambridgepark Drive",
    "Malden High School",
    "One Beacon St",
    "Raymond Park at Walden St",
    "55 Wheeler Street",
    "855 Broadway",
    "Derby Street",
    "Broadway at Gerrish Ave",
    "Centre St at Commonwealth Ave",
    "Broadway at Grafton St",
    "North St at Liberty Hill Ave",
    "Goodhue St at Grove St",
    "American Legion Hwy at Hyde Park Ave",
    "Salem Ferry Landing",
    "Gilman Square T at Medford St",
    "Thetford Ave at Norfolk St",
    "Boynton Yards at 101 South Street",
    "Riverway at Brookline Ave",
    "Watertown City Hall",
    "Chelsea Square",
    "Archdale Rd at Washington St",
    "BCBS Hingham",
    "Pope John High School",
    "Auburndale",
    "Newton Highlands T",
    "Morton St T",
    "Mt. Hope St at Hyde Park Ave",
    "Forest River Park",
    "Bellingham Square",
    "Salem MBTA - Lower Level",
    "Dorchester Ave at King St",
    "Cypress St at Clark Playground",
    "Main Street/Albany Street/Technology Square",
    "Lenox St at Kendall St",
    "Wellington MBTA",
    "Flat 9 at Whittier",
    "Chelsea Station",
    "Brighton Ave at Linden St",
    "Cary Square",
    "Western Ave at Richardson St",
    "Tufts Sq - Main St at Medford St",
    "Marion St at White St",
    "Washington St at Peters Park",
    "Broadway at Kittie Knox Bike Path",
    "Tremont St at Court St",
    "Morton St at Gallivan Blvd",
    "Northern Strand at Main St",
    "Washington Sq",
    "Clinton St at North St",
    "Malden Center T Station",
    "Uphams Corner",
    "Nichols Ave. at Watertown Greenway",
    "Lewis Mall Wharf",
    "Addison St at Saratoga St",
    "Bellevue T Stop",
    "Boston College T",
    "Sumner St at Shirley Ave",
    "American Legion Hwy at Cummins Hwy",
    "Beacon at Walnut",
    "Post Office Square",
    "Blossom St at Charles St",
    "Craigie St at Summer St",
    "Linwood St at Minuteman Bikeway",
    "Salem State University - North Campus",
    "Park St at Norwell St",
    " Broadway and Cabot",
    "Community Life Center",
    "Logan Park",
    "Cummins Highway at Blue Hill Ave T Stop",
    "Jersey St. at Boylston St.",
    "Charles St and Beacon St",
    "Dudley Town Common - Mt Pleasant Ave at Blue Hill Ave",
    "Faneuil St at Market St",
    "8D OPS 01",
    "Brookline Village - Pearl Street at MBTA",
    "Foss Park 2 (temp for winter)",
    "Summer St at Quincy St",
    "515 Somerville Ave (Temp. Winter Location)",
    "Stuart St. at Charles St.",
    "Brigham Cir / Huntington Ave",
    "Christian Science Plaza",
    "Seaport Square - Seaport Blvd. at Boston Wharf",
    "Boylston / Mass Ave",
    "Back Bay / South End Station",
    "The Esplanade - Beacon St. at Arlington St.",
    "Beacon St / Mass Ave",
    "Columbus Ave. at Mass. Ave.",
    "Lewis Wharf - Atlantic Ave.",
    "BIDMC - Brookline at Burlington St",
    "Tremont St / W Newton St",
    "Washington St. at Lenox St.",
    "Innovation Lab - 125 Western Ave. at Batten Way",
    "Newbury St / Hereford St",
    "Roxbury Crossing Station",
    "Charles St at Beacon St",
    "Kenmore Sq / Comm Ave",
    "Mayor Martin J Walsh - 28 State St",
    "Boylston St / Washington St",
    "Allston Green District - Commonwealth Ave & Griggs St",
    "South Station - 700 Atlantic Ave.",
    "Ruggles Station / Columbus Ave.",
    "E. Cottage St at Columbia Rd",
    "Charlestown - Main St at Austin St",
    "Packard's Corner - Comm. Ave. at Brighton Ave.",
    "Harvard Real Estate - Brighton Mills - 370 Western Ave",
    "Tremont St. at Berkeley St.",
    "Boston Public Library - 700 Boylston St.",
    "Charlestown - Warren St at Chelsea St",
    "Jackson Square T at Centre St",
    "Charles Circle - Charles St. at Cambridge St.",
    "Aquarium Station - 200 Atlantic Ave.",
    "West Broadway at Dorchester St",
    "Northeastern U / North Parking Lot",
    "Washington St. at Rutland St.",
    "South Boston Library - 646 East Broadway",
    "Cambridge St. at Joy St.",
    "New Balance - 20 Guest St.",
    "New Balance Store - Boylston at Dartmouth",
    "Boylston at Fairfield",
    "Mass Ave at Newmarket Square",
    "Harvard University Transportation Services - 175 North Harvard St",
    "Buswell St. at Park Dr.",
    "TD Garden - Causeway at Portal Park #1",
    "Boylston St / Berkeley St",
    "Faneuil Hall - Union St. at North St.",
    "HMS / HSPH - Ave. Louis Pasteur at Longwood Ave.",
    "Brookline Village - Pearl Street @ MBTA",
    "Harvard University Housing - 111 Western Ave. at Soldiers Field Park ",
    "Union Square - Brighton Ave. at Cambridge St.",
    "TD Garden - Causeway at Portal Park #2",
    "Prudential Center / Belvidere",
    "Rowes Wharf - Atlantic Ave",
    "Washington St. at Waltham St.",
    "Green St T",
    "Boston Medical Center -  East Concord at Harrison Ave",
    "Curtis Hall at South Street",
    "Chinatown Gate Plaza - Surface Rd. at Beach St.",
    "Upham's Corner - Ramsey St at Dudley St",
    "Mt Pleasant Ave / Dudley Town Common",
    "Longwood Ave / Binney St",
    "JFK / UMASS at MBTA Station",
    "Egleston Square at Columbus Ave",
    "Franklin St. / Arch St.",
    "JP Center - Centre Street at Myrtle Street",
    "Ink Block",
    "Andrew Station - Dorchester Ave at Humboldt Pl",
    "Agganis Arena - 925 Comm Ave.",
    "Somerville Hospital at Highland Ave / Crocker St",
    "Hayes Square at Vine St.",
    "John F Fitzgerald - Surface Road at India Street",
    "Boston Convention & Exhibition Center",
    "Congress / Sleeper",
    "Hyde Square at Barbara St",
    "Cross St. at Hanover St.",
    "Tremont St / West St",
    "Landmark Centre",
    "Dudley Square",
    "Dorchester Ave. at Gillette Park",
    "Colleges of the Fenway",
    "Summer St at Cutter St",
    "Boylston St. at Arlington St.",
    "Seaport Hotel",
    "UMass Boston Integrated Sciences Complex",
    "8D OPS 03",
    "Canal St at Causeway St",
    "Blue Hill Ave at Southwood St",
    "160 Arsenal",
    "Mass Ave at Grafton St",
    "Wasgott Playground",
    "Roseland St At Dorchester Ave",
    "Charles River Greenway - California St. at Fifth Ave",
    "Mass Ave at Broadway",
    "Hyde Park Ave at Arlington St",
    "Tremont St at Hamilton Place",
    "Park Plaza at Charles St",
    "30 Dane St.",
    "Tremont St. at Court St.",
    "Canal St. at Causeway St.",
    "Meaney Playground - Pleasant st at E Cottage St",
    "8D QC Station 01",
    "Boylston St at Charles St (Temp Winter Location)",
    "Franklin Park - Seaver Street at Humbolt Ave",
    "Wentworth Institute of Technology",
    "Brighton Center",
    "Lawn on D",
    "Edwards Playground - Main Street & Eden Street",
    "West Broadway at D Street",
    "Congress St and Northern Ave",
    "Franklin Park Zoo",
    "Heath St at South Huntington",
    "Day Boulevard",
    "Ryan Playground - Dorchester Avenue Station",
    "Savin Hill MBTA Station",
    "Washington St at Griggs Rd",
    "Adams Branch Library",
    "Pearl St at Medford St",
    "Washington St at Bradlee St",
    "Walnut Ave at Crawford St",
    "Roxbury YMCA",
    "Piers Park- Marginal St at East Boston Shipyard",
    "The Eddy at New Street",
    "Oak Square YMCA",
    "Upham's Corner - Columbia Rd",
    "Maverick Sq - Lewis Mall",
    "Grove Hall Library",
    "Market St at Faneuil St",
    "EBNHC - 20 Maverick Sq",
    "Watermark Seaport",
    "Upham's Corner T Stop",
    "Norman St at Kelvin St",
    "Hickey Park",
    "Hyde Square - Centre St at Perkins St",
    "Elevate at One Leighton",
    "Grand Union Blvd at Revolution Dr",
    "Melnea Cass Blvd at Hampden St",
    "Chestnut Hill Ave at Ledgemere Rd",
    "Carr Park",
    "101 Smith Place",
    "Centre St. at Allandale St.",
    "Arsenal on the Charles",
    "Main Street at Carter Street",
    "Beacon St at Hawes St",
    "8D QC Station 02",
    "Test 000e3",
    "Huron Ave. At Vassal Lane",
    "Brookline Village - Station Street @ MBTA TEMPORARY WINTER LOCATION",
    "Boylston St at Arlington St TEMPORARY WINTER LOCATION",
    "Allston Green District - Griggs St at Commonwealth Ave TEMPORARY WINTER LOCATION",
    "Washington Square at Washington St. / Beacon St. TEMPORARY WINTER LOCATION",
    "Charles Circle - Charles St at Cambridge St TEMPORARY WINTER LOCATION",
    "Upham's Corner TEMPORARY WINTER LOCATION",
    "Deerfield St at Commonwealth Ave (former)",
    "Park Plaza at Charles St (former)",
    "Washington St at Egremont Rd (former)",
    "Commonwealth Ave at Kelton St (former)",
    "Blue Hill Ave at Southwood St (former)",
    "Medford St at Charlestown BCYF (former)",
    "Centre St at Seaverns Ave (former)",
    "Harvard St at Greene-Rose Heritage Park (former)",
    "Mass Ave at Hadley/Walden (former)",
    "Charlestown Navy Yard (former)",
    "Boylston St at Jersey St (former)",
    "Harvard Ave at Brainerd Rd (former)",
    "699 Mt Auburn St (former)",
    "Archdale Rd at Washington St (former)",
    "Commonwealth Ave at Chiswick Rd (former)",
    "Main St at Thompson Sq (former)",
    "Washington St at Myrtle St (former)",
    "Huntington Ave at Mass Art (former)",
    "Columbia Rd at Tierney Community Center (former)",
    "Grove St at Community Path (former)",
    "Roslindale Village - South St (former)",
    "Codman Square Library (former)",
    "One Brigham Circle (former)",
    "Bartlett St at John Elliot Sq (former)",
    "Cleveland Circle (former)",
    "Faneuil St at Arlington St (former)",
    "Bennington St at Constitution Beach (former)",
    "Washington St at Talbot Ave (former)",
    "Mattapan Library (former)",
    "Roslindale Village - Washington St (former)",
    "Talbot Ave At Blue Hill Ave (former)",
    "Broadway T Stop (former)",
    "Blue Hill Ave at Almont St (former)",
    "Thetford Ave at Norfolk St (former)",
    "Harrison Ave at Bennet St (former)",
    "Morton St T (former)",
    "Mattapan T Stop (former)",
    "Harrison Ave at Mullins Way (former)",
    "Tremont St at Northampton St (former)",
    "30 Dane St. (former)",
    "Vassal Lane at Tobin/VLUS (former)",
    "High St at Federal St",
    "Staniford St at Merrimac St",
    "Mill St. at Minuteman Bikeway",
    "Centre St at Allandale St",
    "Au Bon Pain Way at Fid Kennedy Ave",
    "Lake St. at Minuteman Bikeway",
    "Shawmut Ave at Herald St",
    "40 Thorndike St",
    "Damrell St at Old Colony",
    "Winthrop Circle",
    "Western Ave at Everett St",
    "Cambridgeside Pl at Land Blvd",
    "Massachusetts Ave at Boylston St.",
    "Swan Place at Minuteman Bikeway",
    "Governors Ave at Lawrence Rd",
    "Craigie & Summer at Conway Park (Temp. Winter Location)",
    "Medford St at Warren St",
    "Northern Strand - West St & Wellington Ave",
    "Washington St at Temple Pl",
    "Stuart St at Church St",
    "Watertown St at 5th Ave",
    "Commercial St at Charter St",
    "780 Morrissey Blvd",
    "Steve Miller Dr at Winthrop St (Medford High)",
    "Revere Beach - Markey Footbridge",
    "615 Broadway",
    "Eliot Circle Revere Beach",
    "Chestnut Hill Ave. at Ledgemere Road",
    "Sennott Park  Broadway at Norfolk Street",
    "Ferry St at Pleasantview Ave",
    "Main St at Beacon St",
    "MTL-ECO4-01",
    "Damrell St at Old Colony Ave",
    "Damrell st at Old Colony Ave",
    "Boylston St at Dartmouth St FORMER",
    "Big Papi Station",
    "Charles St at Pinckney St",
    "Cummins at American Legion",
    "Mobile Temporary Station",
    "Swan Pl. at Minuteman Bikeway",
    "Mobile Temporary Station 2",
    "Park Plaza at Columbus Ave",
    "MTL-ECO5.1-01",
    "Central Square East Boston - Porter Street at London Street",
    "Clarendon St at Commonwealth Ave",
    "Beacon St at Englewood Ave",
    "Staniford at Merrimac",
    "Medford St. at Warren St.",
    "Shawmut Ave. at Herald St.",
}
